[template]
cargo_generate_version = ">=0.10.0"

[placeholders.short-desc]
type = "string"
prompt = "Short description"
default = "TODO"

[placeholders.long-desc]
type = "string"
prompt = "Long description"
default = "TODO"

[placeholders.year]
type = "string"
prompt = "Year"
default = "2024"

[conditional.'crate_type == "lib"']
ignore = [ "src/main.rs" ]

#[conditional.'crate_type == "bin"']
#ignore = [ "src/lib.rs" ]
