[template]
cargo_generate_version = ">=0.10.0"

[hooks]
init = ["init-script.rhai"]
#pre = ["pre-script.rhai"]
#post = ["post-script.rhai"]

[placeholders.short-desc]
type = "string"
prompt = "Short description"
default = "TODO"

[placeholders.long-desc]
type = "string"
prompt = "Long description"
default = "TODO"

[conditional.'crate_type == "lib"']
ignore = [ "src/main.rs" ]
