name: build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
      - name: sccache
        uses: mozilla-actions/sccache-action@v0.0.7
      # - name: dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y libxdo-dev
      - name: rustfmt
        run: cargo fmt --all --check
      - name: clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: test
        run: cargo test
      - name: build
        run: cargo build
      - name: semver-checks
        uses: obi1kenobi/cargo-semver-checks-action@v2

  build-macos:
    runs-on: macOS-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: sccache
        uses: mozilla-actions/sccache-action@v0.0.7
      - name: test
        run: cargo test
      - name: build
        run: cargo build

  build-windows:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: sccache
        uses: mozilla-actions/sccache-action@v0.0.7
      - name: test
        run: cargo test
      - name: build
        run: cargo build
