name: build

permissions:
  contents: read

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: {% raw %}${{ github.workflow }}{% endraw %}-{% raw %}${{ github.ref }}{% endraw %}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  build-linux-plus-checks:
    name: build-linux-plus-checks
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
          persist-credentials: false
      - name: toolchain
        uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
        with:
          components: rustfmt, clippy
      - name: sccache
        uses: mozilla-actions/sccache-action@9e7fa8a12102821edf02ca5dbea1acd0f89a2696 # v0.0.10
      - name: prepare IDA SDK
        env:
          IDASDK_URL: {% raw %}${{ secrets.IDASDK_URL }}{% endraw %}
          IDASDK_PASSWORD: {% raw %}${{ secrets.IDASDK_PASSWORD }}{% endraw %}
        run: |
          curl -o "{% raw %}${{ runner.temp }}{% endraw %}/idasdk.zip" -L "$IDASDK_URL"
          unzip -d "{% raw %}${{ runner.temp }}{% endraw %}" -P "$IDASDK_PASSWORD" "{% raw %}${{ runner.temp }}{% endraw %}/idasdk.zip"
      - name: rustfmt
        run: cargo fmt --all --check
      - name: clippy
        env:
          IDASDKDIR: "{% raw %}${{ runner.temp }}{% endraw %}/idasdk"
        run: cargo clippy --all-targets -- -D warnings
      - name: build
        env:
          IDASDKDIR: "{% raw %}${{ runner.temp }}{% endraw %}/idasdk"
        run: cargo build

  build-macos:
    name: build-macos
    runs-on: macOS-latest
    timeout-minutes: 30
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
          persist-credentials: false
      - name: toolchain
        uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
        with:
          components: rustfmt, clippy
      - name: sccache
        uses: mozilla-actions/sccache-action@9e7fa8a12102821edf02ca5dbea1acd0f89a2696 # v0.0.10
      - name: prepare IDA SDK
        env:
          IDASDK_URL: {% raw %}${{ secrets.IDASDK_URL }}{% endraw %}
          IDASDK_PASSWORD: {% raw %}${{ secrets.IDASDK_PASSWORD }}{% endraw %}
        run: |
          curl -o "{% raw %}${{ runner.temp }}{% endraw %}/idasdk.zip" -L "$IDASDK_URL"
          unzip -d "{% raw %}${{ runner.temp }}{% endraw %}" -P "$IDASDK_PASSWORD" "{% raw %}${{ runner.temp }}{% endraw %}/idasdk.zip"
      - name: build
        env:
          IDASDKDIR: "{% raw %}${{ runner.temp }}{% endraw %}/idasdk"
        run: cargo build

  build-windows:
    name: build-windows
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - name: install clang/llvm
        uses: KyleMayes/install-llvm-action@e0a8dc9cb8a22e8a7696e8a91a4e9581bec13181
        with:
          version: "18.1.8"
          directory: "{% raw %}${{ runner.temp }}{% endraw %}/llvm-18"
      - name: configure clang/llvm environment
        run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
          persist-credentials: false
      - name: toolchain
        uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
        with:
          components: rustfmt, clippy
      - name: sccache
        uses: mozilla-actions/sccache-action@9e7fa8a12102821edf02ca5dbea1acd0f89a2696 # v0.0.10
      - name: prepare IDA SDK
        env:
          IDASDK_URL: {% raw %}${{ secrets.IDASDK_URL }}{% endraw %}
          IDASDK_PASSWORD: {% raw %}${{ secrets.IDASDK_PASSWORD }}{% endraw %}
        run: |
          curl -o "{% raw %}${{ runner.temp }}{% endraw %}/idasdk.zip" -L $env:IDASDK_URL
          unzip -d "{% raw %}${{ runner.temp }}{% endraw %}" -P $env:IDASDK_PASSWORD "{% raw %}${{ runner.temp }}{% endraw %}/idasdk.zip"
      - name: build
        env:
          IDASDKDIR: "{% raw %}${{ runner.temp }}{% endraw %}/idasdk"
        run: cargo build
