name: build

permissions:
  contents: read

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  build-linux:
    name: build-linux
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          submodules: true
          persist-credentials: false
      - name: toolchain
        uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
        with:
          components: rustfmt, clippy
      - name: sccache
        uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad # v0.0.9
      # - name: dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y libxdo-dev
      - name: rustfmt
        run: cargo fmt --all --check
      - name: clippy
        run: cargo clippy --all-targets -- -D warnings
      # - name: nextest
      #   uses: taiki-e/install-action@cargo-nextest
      - name: test
        run: cargo test
      #   run: cargo nextest run
      - name: build
        run: cargo build
      - name: semver-checks
        uses: obi1kenobi/cargo-semver-checks-action@5b298c9520f7096a4683c0bd981a7ac5a7e249ae # v2.8

  build-macos:
    name: build-macos
    runs-on: macOS-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          submodules: true
          persist-credentials: false
      - name: toolchain
        uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
      - name: sccache
        uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad # v0.0.9
      # - name: nextest
      #   uses: taiki-e/install-action@cargo-nextest
      - name: test
        run: cargo test
      #   run: cargo nextest run
      - name: build
        run: cargo build

  build-windows:
    name: build-windows
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          submodules: true
          persist-credentials: false
      - name: toolchain
        uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
      - name: sccache
        uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad # v0.0.9
      # - name: nextest
      #   uses: taiki-e/install-action@cargo-nextest
      - name: test
        run: cargo test
      #   run: cargo nextest run
      - name: build
        run: cargo build
