name: doc

permissions:
  contents: read

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write # needed to push generated rustdoc to the gh-pages branch
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
      - name: prepare IDA SDK
        env:
          IDASDK_URL: ${{ secrets.IDASDK_URL }}
          IDASDK_PASSWORD: ${{ secrets.IDASDK_PASSWORD }}
        run: |
          curl -o "${{ runner.temp }}/idasdk.zip" -L "$IDASDK_URL"
          unzip -d "${{ runner.temp }}" -P "$IDASDK_PASSWORD" "${{ runner.temp }}/idasdk.zip"
      - name: generate documentation
        env:
          IDASDKDIR: "${{ runner.temp }}/idasdk"
        run: cargo doc
      - name: git configuration
        run: |
          git config user.name "GitHub Actions for {{project-name}}"
          git config user.email "raptor@0xdeadbeef.info"
          git config push.autosetupremote true
      - name: deploy
        run: |
          git fetch --all
          git checkout gh-pages
          cp -R target/doc/* .
          rm -rf target Cargo.lock
          git add .
          git config push.autosetupremote true
          git commit -m 'update documentation'
          git push
