name: doc

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: prepare IDA SDK
        env:
          IDASDK_URL: ${{ secrets.IDASDK_URL }}
          IDASDK_PASSWORD: ${{ secrets.IDASDK_PASSWORD }}
        run: |
          curl -o "${{ runner.temp }}/idasdk.zip" -L "$IDASDK_URL"
          unzip -d "${{ runner.temp }}" -P "$IDASDK_PASSWORD" "${{ runner.temp }}/idasdk.zip"
      - name: generate documentation
        env:
          IDASDKDIR: "${{ runner.temp }}/idasdk"
        run: cargo doc
      - name: git configuration
        run: |
          git config user.name "GitHub Actions for {{project-name}}"
          git config user.email "raptor@0xdeadbeef.info"
          git config push.autosetupremote true
      - name: deploy
        run: |
          git fetch --all
          git checkout gh-pages
          cp -R target/doc/* .
          rm -rf target Cargo.lock
          git add .
          git config push.autosetupremote true
          git commit -m 'update documentation'
          git push
